In [53]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [59]:
import numpy as np
array0d=(42)
print(array0d)

42


In [57]:
import numpy as np
array1d=np.array([1,2,3,4,5,6])
print(array1d)

[1 2 3 4 5 6]


In [61]:
import numpy as np
array2d=np.array([[1,2,3,4],[5,6,7,8]])
print(array2d)

[[1 2 3 4]
 [5 6 7 8]]


In [31]:
import numpy as np
array3d=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(array3d)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


In [65]:
import numpy as np 
array1d=np.array([1,2,3])
print(array1d)
print(array1d.dtype)

[1 2 3]
int32


In [69]:
import numpy as np
type1= np.array([1, 2, 3, 4, 5, 6])
type2 =np.array([1.5, 2.5, 0.5, 6])
type3= np.array(['a', 'b', 'c'])
type4 =np.array(["Canada", "Australia"])
type5 =np.array([555, 666], dtype=float)
type6 =np.array(["Canada", "Australia"],dtype="U5")
print(type1.dtype)
print(type2.dtype)
print(type3.dtype)
print(type4.dtype)
print(type5.dtype)
print(type6)

int32
float64
<U1
<U9
float64
['Canad' 'Austr']


In [67]:
import numpy as np
array1d=np.array([1,2,3,4,5,6])
array2d=np.array([[1,2,3],[4,5,6]])
array3d=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])

print(array1d.shape)
print(array2d.shape)
print(array3d.shape)

(6,)
(2, 3)
(2, 2, 4)


In [71]:
import numpy as np
array1d=np.array([1,2,3,4,5,6])
array2d=np.array([[1,2,3],[4,5,6]])
array3d=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(array1d.ndim)
print(array2d.ndim)
print(array3d.ndim)

1
2
3


In [75]:
import numpy as np
thearray=np.array([1,2,3,4,5,6,7,8])
thearray=thearray.reshape(4,2)
print(thearray)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [73]:
import numpy as np
thearray=np.array([1,2,3,4,5,6,7,8])
thearray=thearray.reshape(2,4)
print(thearray)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
import numpy as np
thearray=np.array([1,2,3,4,5,6,7,8])
thearray=thearray.reshape(8,1)
print(thearray)

In [ ]:
import numpy as np
thearray=np.array([1,2,3,4,5,6,7,8])
thearray.resize(4)
print(thearray)

In [ ]:
import numpy as np
array2d=np.array([[1,2,3,],[1,2,3]])
print(array2d)

In [77]:
import numpy as np
array1d=np.array([[1,2,3],[1,2,3]])
array2d=np.array([[1,2,3],[1,2,3]])
print(np.union1d(array1d,array2d))

[1 2 3]


In [ ]:
import numpy as np
np.eye((20,20), dtype="int")

In [ ]:
import numpy as np 
np.eye(4)

In [79]:
import numpy as np
np.empty((3,3),dtype="int")

array([[    0,     1,     0],
       [  544,  1552,     0],
       [  768, 32762,     0]])

In [ ]:
import numpy as np
np.ones((3,3),dtype="int")

In [81]:
import numpy as np
matrix=np.arange(1,226).reshape(15, 15)
print("Orgnl matrix:")
print(matrix)
matrix[::2, :]=0
print("\n Modified matrix:")
print(matrix)

Orgnl matrix:
[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15]
 [ 16  17  18  19  20  21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40  41  42  43  44  45]
 [ 46  47  48  49  50  51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70  71  72  73  74  75]
 [ 76  77  78  79  80  81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100 101 102 103 104 105]
 [106 107 108 109 110 111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130 131 132 133 134 135]
 [136 137 138 139 140 141 142 143 144 145 146 147 148 149 150]
 [151 152 153 154 155 156 157 158 159 160 161 162 163 164 165]
 [166 167 168 169 170 171 172 173 174 175 176 177 178 179 180]
 [181 182 183 184 185 186 187 188 189 190 191 192 193 194 195]
 [196 197 198 199 200 201 202 203 204 205 206 207 208 209 210]
 [211 212 213 214 215 216 217 218 219 220 221 222 223 224 225]]

 Modified matrix:
[[  0   0   0   0   0

In [90]:
import numpy as np
np.ones((14,14), dtype="int")

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [96]:
import numpy as np
matrix=np.arange(1,26).reshape(1)
print(matrix)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [3]:
import numpy as np
mn=np.arange(1,26)
print(mn)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


In [33]:
import numpy as np
np.ones((12,12),dtype="int")

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [59]:
import numpy as np
matrix=np.arange(1,10).reshape(3,3)
print(matrix)
print("alag he")
matrix[:3,::2]
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
alag he
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [61]:
import numpy as np
array1=np.array([1,2,3,4],[7,8,9,10])
array2=np.array([5,6,7,8],[11,12,13,14])
arrayA=np.append


[ 6  8 10 12]


In [3]:
import numpy as np
array1=np.array([1,2,3,4])
array2=np.array([5,6,7,8])
print(array1)
print(array2)


[1 2 3 4]
[5 6 7 8]


In [15]:
arrayc=np.concatenate((array1,array2))
print(arrayc)

[[ 1  2  3  4]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [13 14 15 16]]


In [145]:
import numpy as np
array1=np.array([[1,2,3,4],[9,10,11,12]])
array2=np.array([[5,6,7,8],[13,14,15,16]])
print(array1)
print(array2)
arrayA=np.append(array1,array2,axis=1)
print(arrayA)

[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 5  6  7  8]
 [13 14 15 16]]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [45]:
import numpy as np
array1=np.array([[1,2,3,4],[9,10,11,12]])
array2=np.array([[5,6,7,8],[13,14,15,16]])
print(array1)
print(array2)
print("---------------")
arryv=np.hstack((array1,array2))
print(arryv)
print("------------------")
arrayz=np.vstack((array1,array2))
print(arrayz)
print("-------------------")
arrayl=np.dstack((array1,array2))
print(arrayl)

[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 5  6  7  8]
 [13 14 15 16]]
---------------
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
------------------
[[ 1  2  3  4]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [13 14 15 16]]
-------------------
[[[ 1  5]
  [ 2  6]
  [ 3  7]
  [ 4  8]]

 [[ 9 13]
  [10 14]
  [11 15]
  [12 16]]]


In [55]:
import numpy as np
array1=np.array([1,2,3,4],)
array2=np.array([5,6,7,8])
print(array1)
print(array2)



[1 2 3 4]
[5 6 7 8]


In [93]:
import numpy as np
np.ones((12,1),dtype="int")

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [81]:
import numpy as np
np.ones((12,12),dtype="int")

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [95]:
import numpy as np
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [103]:
import numpy as np
np.full((3,3),6)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [135]:
import numpy as np
array1=np.array([[[1,2,3,4],[9,10,11,12]],[[1,2,3,4],[4,5,6,7]]])
array2=np.array([[[5,6,7,8],[13,14,15,16]],[[3,4,5,6],[4,5,6,7]]])
print(array1)
print(array2)
print("-------------------")
arrayA=np.append(array1,array2,axis=2)
print(arrayA)

[[[ 1  2  3  4]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 4  5  6  7]]]
[[[ 5  6  7  8]
  [13 14 15 16]]

 [[ 3  4  5  6]
  [ 4  5  6  7]]]
-------------------
[[[ 1  2  3  4  5  6  7  8]
  [ 9 10 11 12 13 14 15 16]]

 [[ 1  2  3  4  3  4  5  6]
  [ 4  5  6  7  4  5  6  7]]]


In [139]:
import numpy as np
print(np.identity(4))


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [1]:
import pandas as pd
ser1=pd.series(["l"]*4)
print(ser1)

AttributeError: module 'pandas' has no attribute 'series'